### ISSUE TITLE
Showing nft claiming failed after doing all the tasks sucessfully.

### ISSUE THREAD

**Issue by anipaul2** [CreatorOS/polygon-quest-one-simple-storage#4]
![Screenshot (426)](https://user-images.githubusercontent.com/74004409/154844324-0f17404d-96d2-4e7c-a054-89e24f981402.png)

**Comment by SahilVasava** [comment]
@anipaul2 The transaction are getting dropped. We are working on it. 
Bear with us, you will be able to claim with same tweet url once it is up.

**Comment by anipaul2** [comment]
> @anipaul2 The transaction are getting dropped. We are working on it. Bear with us, you will be able to claim with same tweet url once it is up.

Cool, thanks.
